config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
  get "/search", to: "pages#search"
  get "/results", to: "pages#results"
  resources :movies, only: [ :show, :index ]

  # resources :users, only: [:show]

  resources :favorite_movies_by_users, path: "favorite", only: [ :index, :create, :destroy ]
  resources :soon_to_watch_movies_by_users, path: "soon_to_watch", only: [ :index, :create, :destroy ]
  resources :already_watched_movies_by_users, path: "already_watched", only: [ :index, :create ]

  match "*unmatched", to: "application#not_found", via: :all
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.movies.all.order(created_at: :desc)
  end

  def show
    @movie = Movie.find_by(api_movie_id: params[:id])

    unless @movie
      redirect_to request.referer || search_path, alert: "Movie not found"
      return
    end

    load_show_data

    if @movie.api_rating.blank?
      # real API call
      details = MovieApi.get_movies_by_id(@movie.api_movie_id)

      # mock API data call
      # file_path = Rails.root.join("lib", "assets", "search_id.json")
      # details = JSON.parse(File.read(file_path))

      # add rating to movie object
      @movie.update(
        api_rating: details["Ratings"].first["Value"]
      )
    end
  end

  private

  def load_show_data
    @my_favorite_movies = current_user.favorite_movies
    @my_favorite_movie = current_user.favorite_movies_by_users.find_by(movie_id: @movie.id)
    @my_soon_to_watch_movies = current_user.soon_to_watch_movies
    @my_soon_to_watch_movie = current_user.soon_to_watch_movies_by_users.find_by(movie_id: @movie.id)
    @my_already_watched_movies = current_user.already_watched_movies
    @my_already_watched_movie = current_user.already_watched_movies_by_users.find_by(movie_id: @movie.id)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/show.html.erb
<body class="bg-cover bg-[url('/dark-vip-cinema-studio-still-life.jpg')] overflow-x-hidden h-screen">

  <%= link_to root_path do %>
    <img src="/result (1).png" class="w-3xs fixed left-60 mt-4 cursor-pointer">
  <% end %>

 <div class="fixed right-0 mt-4 mr-45 inline-flex justify-center items-center py-1 px-3 text-base font-medium text-center text-white rounded-lg hover:bg-gray-200 hover:text-gray-800 border-4 border-gray-200">
    <%= link_to 'Home', search_path, class: "cursor-pointer" %>
  </div>


  <div class="mt-20 mx-auto max-w-4xl p-6 bg-white bg-opacity-90 rounded-lg shadow-lg">
    <h1 class="text-3xl font-bold text-center mb-6"><%= @movie.title %></h1>
    <div class="flex justify-center mb-6">
      <img src=<%= @movie.poster %> alt="" class="rounded-lg shadow-md">
    </div>

      <% if @my_already_watched_movies.include?(@movie) %>
        <% if @my_favorite_movies.include?(@movie) %>
          <div class="text-center">
            <%= button_to 'Remove from favorite', favorite_movies_by_user_path(movie_id: @movie.id), method: :delete, class: "px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-all duration-300 ease-in-out transform hover:scale-105 hover:shadow-lg cursor-pointer" %>
          </div>
        <% else %>
          <div class="text-center">
            <%= button_to 'Add to favorite', favorite_movies_by_users_path(movie_id: @movie.id), method: :post, class: "px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-all duration-300 ease-in-out transform hover:scale-105 hover:shadow-lg cursor-pointer" %>
          </div>
        <% end %>

        <div class="mt-4 text-center text-gray-700"> Watched <%= @my_already_watched_movies.where(id: @movie.id).count %> time/s </div>
        
        
        <div class="mt-2">
          <div class="flex items-center justify-center">
            <p class="ms-2 text-sm font-bold text-gray-900">Internet Movie Database Rating:</p>
            <svg class="w-4 h-4 text-yellow-300 me-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
            </svg>
            <p class="text-sm font-bold text-gray-900"><%= @movie.api_rating %></p>
          </div>
          <% if @my_already_watched_movie.personal_rating.present? %>
            <div class="flex items-center justify-center">
              <p class="ms-2 text-sm font-bold text-gray-900">Personal Rating:</p>
              <svg class="w-4 h-4 text-yellow-300 me-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                  <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
              </svg>
              <p class="text-sm font-bold text-gray-900"><%= @my_already_watched_movie.personal_rating %></p>
            </div>
          <% end %>
          <% if @my_already_watched_movie.remarks.present? %>
            <div class="flex items-center justify-center">
              <p class="text-gray-500"><%= @my_already_watched_movie.remarks %></p>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="flex items-center justify-center">
            <p class="ms-2 text-sm font-bold text-gray-900">Internet Movie Database Rating:</p>
            <svg class="w-4 h-4 text-yellow-300 me-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
            </svg>
            <p class="text-sm font-bold text-gray-900"><%= @movie.api_rating %></p>
          </div>
      <% end %>

      <% if @my_soon_to_watch_movies.include?(@movie) %>
        <div class="mt-4 text-center">
          <%= button_to 'Remove from soon_to_watch', soon_to_watch_movies_by_user_path(movie_id: @movie.id), method: :delete, class: "mb-2 px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-all duration-300 ease-in-out transform hover:scale-105 hover:shadow-lg cursor-pointer" %>
          <button onClick="document.getElementById('watched_form').style.display = 'block'" class="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-all duration-300 ease-in-out transform hover:scale-105 hover:shadow-lg cursor-pointer"> 
            Move to already watched list
          </button>
        </div>
        <%= render 'already_watched_movies_by_users/form' %>
      <% else %>
        <div class="mt-6 text-center">
          <%= button_to 'Add to soon to watch list', soon_to_watch_movies_by_users_path(movie_id: @movie.id), method: :post, class: "px-4 py-2 bg-yellow-500 text-white rounded-lg hover:bg-yellow-600 transition-all duration-300 ease-in-out transform hover:scale-105 hover:shadow-lg cursor-pointer" %>
        </div>
      <% end %>

      <div class="mt-4 sticky bottom-0 left-0 z-50 w-full h-16 bg-white border-t border-gray-200">
        <div class="grid h-full max-w-lg grid-cols-3 mx-auto">
            <%= link_to soon_to_watch_movies_by_users_path, class: "inline-flex flex-col items-center justify-center font-medium px-5 hover:bg-gray-50 group cursor-pointer" do %>
                <svg class="w-5 h-5 mb-1 text-gray-500 group-hover:text-blue-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm3.982 13.982a1 1 0 0 1-1.414 0l-3.274-3.274A1.012 1.012 0 0 1 9 10V6a1 1 0 0 1 2 0v3.586l2.982 2.982a1 1 0 0 1 0 1.414Z"/>
                </svg>
                <span class="text-sm text-gray-500 group-hover:text-blue-600">Soon to watch</span>
            <% end %>
            <%= link_to already_watched_movies_by_users_path, class: "inline-flex flex-col items-center justify-center font-medium px-5 hover:bg-gray-50 group cursor-pointer" do %>
                <svg class="w-5 h-5 mb-1 text-gray-500 group-hover:text-blue-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 640 512">
                    <path d="M96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM0 482.3C0 383.8 79.8 304 178.3 304l91.4 0C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7L29.7 512C13.3 512 0 498.7 0 482.3zM625 177L497 305c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L591 143c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"/>
                </svg>
                <span class="text-sm text-gray-500 group-hover:text-blue-600">Already watched</span>
            <% end %>
            <%= link_to favorite_movies_by_users_path, class: "inline-flex flex-col items-center justify-center font-medium px-5 hover:bg-gray-50 group cursor-pointer" do %>
                <svg class="w-6 h-6 mb-1 text-gray-500 group-hover:text-blue-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                    <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
                <span class="text-sm text-gray-500 group-hover:text-blue-600">Favorites</span>
            <% end %>
        </div>
    </div>
  </div>
</body>